# Generated by Django 4.2.7 on 2023-11-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('MP3', 'MP3'), ('FLAC', 'FLAC')], default='MP3', max_length=4)),
                ('tracklist', models.JSONField()),
            ],
        ),
    ]
