# Generated by Django 4.2.7 on 2023-11-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_on_device',
            field=models.BooleanField(default=False),
        ),
    ]
