# Generated by Django 4.2.7 on 2023-11-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_organizer', '0002_album_is_on_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='format',
            new_name='file_format',
        ),
    ]
